### ISSUE TITLE
Latest develop commit breaks compilation with msys2 gcc on Windows

### ISSUE THREAD

**Issue by agraef** [danomatika/joyosc#24]
Rev. 78f97111ac52d13759bd240e962bc6cb88cc4cb6 breaks the msys2 build with gcc 14.2.0 (which is the latest version on Windows). Previous commit still built fine, so just reverting that commit will fix the issue.

I'm not sure what's going on there, the same source compiles fine on Linux (with gcc 14.2.1) and macOS (with clang 15.0.0).

Abridged build log (mingw 64 bit):

~~~make
Making all in lib
make[1]: Entering directory '/home/ag/joyosc/lib'
make[2]: Entering directory '/home/ag/joyosc/lib'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/ag/joyosc/lib'
make[1]: Leaving directory '/home/ag/joyosc/lib'
Making all in src
make[1]: Entering directory '/home/ag/joyosc/src'
make  all-recursive
make[2]: Entering directory '/home/ag/joyosc/src'
Making all in joyosc
make[3]: Entering directory '/home/ag/joyosc/src/joyosc'
g++ -DHAVE_CONFIG_H -I. -I../../src   -IC:/msys64/mingw64/include/SDL2 -Dmain=SDL_main  -IC:/msys64/mingw64/include/SDL2 -Dmain=SDL_main   -I../../lib/cpphelpers -g -O2 -MT App.o -MD -MP -MF .deps/App.Tpo -c -o App.o App.cpp
App.cpp: In member function 'bool App::loadXMLFile(const std::string&)':
App.cpp:216:9: error: reference to 'XMLDocument' is ambiguous
  216 |         XMLDocument *doc = new XMLDocument;
      |         ^~~~~~~~~~~
In file included from Common.h:37,
                 from App.h:25,
                 from App.cpp:23:
C:/msys64/mingw64/include/tinyxml2.h:1720:20: note: candidates are: 'class tinyxml2::XMLDocument'
 1720 | class TINYXML2_LIB XMLDocument : public XMLNode
      |                    ^~~~~~~~~~~
In file included from C:/msys64/mingw64/include/urlmon.h:450,
                 from C:/msys64/mingw64/include/objbase.h:163,
                 from C:/msys64/mingw64/include/ole2.h:17,
                 from C:/msys64/mingw64/include/wtypes.h:13,
                 from C:/msys64/mingw64/include/winscard.h:10,
                 from C:/msys64/mingw64/include/windows.h:97,
                 from C:/msys64/mingw64/include/winsock2.h:23,
                 from C:/msys64/mingw64/include/lo/lo_endian.h:24,
                 from C:/msys64/mingw64/include/lo/lo.h:28,
                 from Common.h:35:
C:/msys64/mingw64/include/msxml.h:292:27: note:                 'typedef class XMLDocument XMLDocument'
  292 | typedef class XMLDocument XMLDocument;
      |                           ^~~~~~~~~~~
App.cpp:216:22: error: 'doc' was not declared in this scope
  216 |         XMLDocument *doc = new XMLDocument;
      |                      ^~~
App.cpp:216:32: error: reference to 'XMLDocument' is ambiguous
  216 |         XMLDocument *doc = new XMLDocument;
      |                                ^~~~~~~~~~~
C:/msys64/mingw64/include/tinyxml2.h:1720:20: note: candidates are: 'class tinyxml2::XMLDocument'
 1720 | class TINYXML2_LIB XMLDocument : public XMLNode
      |                    ^~~~~~~~~~~
C:/msys64/mingw64/include/msxml.h:292:27: note:                 'typedef class XMLDocument XMLDocument'
  292 | typedef class XMLDocument XMLDocument;
      |                           ^~~~~~~~~~~
App.cpp:276:18: error: type '<type error>' argument given to 'delete', expected pointer
  276 |         if(doc) {delete doc;}
      |                  ^~~~~~~~~~
App.cpp:280:18: error: type '<type error>' argument given to 'delete', expected pointer
  280 |         if(doc) {delete doc;}
      |                  ^~~~~~~~~~
make[3]: *** [Makefile:482: App.o] Error 1
make[3]: Target 'all' not remade because of errors.
make[3]: Leaving directory '/home/ag/joyosc/src/joyosc'
Making all in lsjs
make[3]: Entering directory '/home/ag/joyosc/src/lsjs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ag/joyosc/src/lsjs'
make[3]: Entering directory '/home/ag/joyosc/src'
make[3]: Leaving directory '/home/ag/joyosc/src'
make[2]: *** [Makefile:389: all-recursive] Error 1
make[2]: Leaving directory '/home/ag/joyosc/src'
make[1]: *** [Makefile:328: all] Error 2
make[1]: Leaving directory '/home/ag/joyosc/src'
Making all in data
make[1]: Entering directory '/home/ag/joyosc/data'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ag/joyosc/data'
make[1]: Entering directory '/home/ag/joyosc'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/ag/joyosc'
make: *** [Makefile:465: all-recursive] Error 1
make: Target 'all' not remade because of errors.
~~~

**Comment by danomatika** [comment]
This should be fixed in develop.

**Comment by danomatika** [comment]
Er, yes, I forgot to finish this. A commit should be there now and I added `develop` to the CI build.

**Comment by agraef** [comment]
Fixed, thanks!
